# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to increment (major, minor or patch)'
        required: true
        default: 'patch'

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
    - run: |
        if [[ "$VERSION" != "major" ]] && [[ "$VERSION" != "minor" ]] && [[ "$VERSION" != "patch" ]]; then
          echo "Input should be either 'major', 'minor' or 'patch'"
          exit 1
        fi
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm version $VERSION
