name: Deploy Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to increment (major, minor or patch)'
        required: true
        default: 'patch'
permissions:
  contents: write
jobs:
  version:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    outputs:
      tag: ${{ steps.get-tag.outputs.TAG }}
    steps:
    - run: |
        if [[ "$VERSION" != "major" ]] && [[ "$VERSION" != "minor" ]] && [[ "$VERSION" != "patch" ]]; then
          echo "Input should be either 'major', 'minor' or 'patch'"
          exit 1
        fi
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4.2.0
      with:
        node-version-file: package.json
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
    - run: npm run check
    - run: npm version "${{ github.event.inputs.version }}" --no-git-tag-version
    - id: get-tag
      run: |
        echo "TAG=$(jq -r '.version' < package.json)" >> $GITHUB_OUTPUT
    - name: Commit Version Bump
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "bump: version to ${{ steps.get-tag.outputs.TAG }}"
        git push
    - name: Create Github Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "${{ steps.get-tag.outputs.TAG }}" --title "Version ${{ steps.get-tag.outputs.TAG }}" --generate-notes --target "${{ github.ref }}"
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
