name: Deploy Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to increment (major, minor or patch)'
        required: true
        default: 'patch'

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
    - run: |
        if [[ "$VERSION" != "major" ]] && [[ "$VERSION" != "minor" ]] && [[ "$VERSION" != "patch" ]]; then
          echo "Input should be either 'major', 'minor' or 'patch'"
          exit 1
        fi
    - run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm version $VERSION
